### ISSUE TITLE
includes这些内置函数没有转换

### ISSUE THREAD

**Issue by c050820063** [CroatiaParanoia/ffformat#1]
`const isCompositeType = (type: symbol) => {
  return [T.array, T.object].includes(type);
};`

**Comment by croatialu** [comment]
不好意思哈哈哈，最近几天没怎么注意github 。
这个问题能麻烦描述得详细点嘛， 我这边还没get到点QAQ

**Comment by c050820063** [comment]
之前使用webpack打出来的包没有将includes这些内置函数转换，低版本会有兼容性问题

**Comment by croatialu** [comment]
soga ，目前的打包对外输出的是只支持到es5版本的， 如果想要兼容更低的， 需要开发者用自身项目的的构建规则去构建依赖里的这个包，而不是由第三方库来构建兼容性更强的包。（对于大多用户来说可能需要适配的浏览器已经支持了这些语法，而此时加入polyfill 的话就没有任何意义，反而增加包体积大小）

所以此问题我个人的建议是 在你项目中， 用自己项目的打包规则， 去对此包进行一个二次打包，以支持 `es3` 规范

**Comment by c050820063** [comment]
includes不是es6的吗

**Comment by croatialu** [comment]
看了下， 确实是属于es6的， 但是我认为第三方库只需要转译语法糖为语法就可以了， 其他的高级api特性， 需要做兼容的， 使用方去使用babel + corejs 就可以了。

如果你需要在项目做兼容的话， 可以：

1. 安装依赖
``` shell
yarn add @babel/core @babel/plugin-transform-runtime @babel/preset-env babel-loader --dev

yarn add core-js@3

```
2. 项目根目录建立 babel.config.json
``` json
{
  "presets": [
    [
      "@babel/env",
      {
        "modules": false,
        "corejs": {
          "version": 3
        },
        "targets": {
          "ie": 9,
          "browsers": "> 0.5%"
        },
        "useBuiltIns": "usage"
      }
    ]
  ],
  "plugins": ["@babel/transform-runtime"]
}
```
3. webpack.config.js 使用babel-loader
``` javascript
module.exports = {
  ...
    module: {
      rules: [
          ...
          {
            test: /\.js$/,
            use: 'babel-loader',
            include: [
              path.resolve(__dirname, "./src"),
              path.resolve(__dirname, "node_modules/ffformat"),
            ],
          }
          ...
        ]
    }
  ...
}
```
这是在打包的时候按需引入polyfill。

另外的还有全量引入以及动态引入（页面加入脚本外链， 根据请求头的 userAgent 去返回该版本浏览器所缺少的polyfill）

**Comment by croatialu** [comment]
老哥， 如果这个没有问题的话， 我将会在今晚把这个问题关掉了哦

**Comment by croatialu** [comment]
高级api 由使用方决定是否使用 polyfill， 库仅提供语法糖的转换来做兼容性的折中方案。
